package hsma.ss2018.informatik.igt.kohler.javawithhibernate;

import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.CustomerRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.DistrictRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.ItemRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.OrderlineRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.OrderRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.StockRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.WarehouseRepository;


public class Main {
    public static void main (String[] args) {

        // CREATE WAREHOUSES
        WarehouseRepository.createWarehouse("Bergwald", "Fritz Falter");
        WarehouseRepository.createWarehouse("Echtwald", "Helga Hehl");

        // CREATE DISTRICTS
        DistrictRepository.createDistrict("Tellerheim", 10.0, 1);
        DistrictRepository.createDistrict("Gabelheim", 20.0, 1);
        DistrictRepository.createDistrict("Messerheim", 30.0, 1);
        DistrictRepository.createDistrict("Lichtheim", 40.0, 1);
        DistrictRepository.createDistrict("Loeffelheim", 50.0, 1);
        DistrictRepository.createDistrict("Tischheim", 60.0, 2);
        DistrictRepository.createDistrict("Sesselheim", 70.0, 2);
        DistrictRepository.createDistrict("Couchheim", 80.0, 2);
        DistrictRepository.createDistrict("Kastenheim", 90.0, 2);
        DistrictRepository.createDistrict("Papierheim", 100.0, 2);
        
        // CREATE ITEMS 
        ItemRepository.createItem("Monitor", 10.0);
        ItemRepository.createItem("Mouse", 20.0);
        ItemRepository.createItem("Keyboard" 30.0);

        // CREATE CUSTOMERS
        CustomerRepository.createCustomer("Emil", "Estermann", "Lessingstrasse 1", "0621 34562635", "123456789123", 1);
        CustomerRepository.createCustomer("Tina", "Tinker", "Bullenstrasse 2", "0621 34562636", "123456789124", 1);
        CustomerRepository.createCustomer("Franz", "Trulla", "Reisstrasse 5", "0621 34562637", "123456789125", 1);
        CustomerRepository.createCustomer("Jessica", "Blau", "Bildstrasse 5", "0621 34562638", "123456789126", 1);
        CustomerRepository.createCustomer("Tim", "Rot", "Kamerastrasse 5", "0621 34562639", "123456789127", 1);
        CustomerRepository.createCustomer("Eva", "Gelb", "Lichtstrasse 5", "0621 34562640", "123456789128", 2);
        CustomerRepository.createCustomer("Alex", "Orange", "Schalterstrasse 5", "0621 34562641", "123456789129", 2);
        CustomerRepository.createCustomer("Lara", "Lila", "Meterstrasse 5", "0621 34562642", "123456789130", 2);
        CustomerRepository.createCustomer("Felix", "Magenta", "Kaltstrasse 5", "0621 34562643", "123456789131", 2);
        CustomerRepository.createCustomer("Katrin", "Cyan", "Warmstrasse 5", "0621 34562644", "123456789132", 2);

        // CREATE ORDER LINES
        OrderlineRepository.createOrderline(1, 1, 3);
        OrderlineRepository.createOrderline(1, 2, 1);
        OrderlineRepository.createOrderline(1, 3, 2);
        OrderlineRepository.createOrderline(2, 1, 3);
        OrderlineRepository.createOrderline(2, 2, 1);
        OrderlineRepository.createOrderline(2, 3, 2);
        OrderlineRepository.createOrderline(3, 1, 3);
        OrderlineRepository.createOrderline(3, 2, 1);
        OrderlineRepository.createOrderline(3, 3, 2);
        OrderlineRepository.createOrderline(4, 1, 3);
        OrderlineRepository.createOrderline(4, 2, 1);
        OrderlineRepository.createOrderline(4, 3, 2);
        OrderlineRepository.createOrderline(5, 1, 3);
        OrderlineRepository.createOrderline(5, 2, 1);
        OrderlineRepository.createOrderline(5, 3, 2);
        OrderlineRepository.createOrderline(6, 1, 3);
        OrderlineRepository.createOrderline(6, 2, 1);
        OrderlineRepository.createOrderline(6, 3, 2);
        OrderlineRepository.createOrderline(7, 1, 3);
        OrderlineRepository.createOrderline(7, 2, 1);
        OrderlineRepository.createOrderline(7, 3, 2);
        OrderlineRepository.createOrderline(8, 1, 3);
        OrderlineRepository.createOrderline(8, 2, 1);
        OrderlineRepository.createOrderline(8, 3, 2);
        OrderlineRepository.createOrderline(9, 1, 3);
        OrderlineRepository.createOrderline(9, 2, 1);
        OrderlineRepository.createOrderline(9, 3, 2);
        OrderlineRepository.createOrderline(10, 1, 3);
        OrderlineRepository.createOrderline(10, 2, 1);
        OrderlineRepository.createOrderline(10, 3, 2);
        OrderlineRepository.createOrderline(11, 1, 3);
        OrderlineRepository.createOrderline(11, 2, 1);
        OrderlineRepository.createOrderline(11, 3, 2);
        OrderlineRepository.createOrderline(12, 1, 3);
        OrderlineRepository.createOrderline(12, 2, 1);
        OrderlineRepository.createOrderline(12, 3, 2);
        OrderlineRepository.createOrderline(13, 1, 3);
        OrderlineRepository.createOrderline(13, 2, 1);
        OrderlineRepository.createOrderline(13, 3, 2);
        OrderlineRepository.createOrderline(14, 1, 3);
        OrderlineRepository.createOrderline(14, 2, 1);
        OrderlineRepository.createOrderline(14, 3, 2);
        OrderlineRepository.createOrderline(15, 1, 3);
        OrderlineRepository.createOrderline(15, 2, 1);
        OrderlineRepository.createOrderline(15, 3, 2);
        OrderlineRepository.createOrderline(16, 1, 3);
        OrderlineRepository.createOrderline(16, 2, 1);
        OrderlineRepository.createOrderline(16, 3, 2);
        OrderlineRepository.createOrderline(17, 1, 3);
        OrderlineRepository.createOrderline(17, 2, 1);
        OrderlineRepository.createOrderline(17, 3, 2);
        OrderlineRepository.createOrderline(18, 1, 3);
        OrderlineRepository.createOrderline(18, 2, 1);
        OrderlineRepository.createOrderline(18, 3, 2);
        OrderlineRepository.createOrderline(19, 1, 3);
        OrderlineRepository.createOrderline(19, 2, 1);
        OrderlineRepository.createOrderline(19, 3, 2);
        OrderlineRepository.createOrderline(20, 1, 3);
        OrderlineRepository.createOrderline(20, 2, 1);
        OrderlineRepository.createOrderline(20, 3, 2);
        OrderlineRepository.createOrderline(21, 1, 3);
        OrderlineRepository.createOrderline(21, 2, 1);
        OrderlineRepository.createOrderline(21, 3, 2);
        OrderlineRepository.createOrderline(22, 1, 3);
        OrderlineRepository.createOrderline(22, 2, 1);
        OrderlineRepository.createOrderline(22, 3, 2);
        OrderlineRepository.createOrderline(23, 1, 3);
        OrderlineRepository.createOrderline(23, 2, 1);
        OrderlineRepository.createOrderline(23, 3, 2);
        OrderlineRepository.createOrderline(24, 1, 3);
        OrderlineRepository.createOrderline(24, 2, 1);
        OrderlineRepository.createOrderline(24, 3, 2);
        OrderlineRepository.createOrderline(25, 1, 3);
        OrderlineRepository.createOrderline(25, 2, 1);
        OrderlineRepository.createOrderline(25, 3, 2);
        OrderlineRepository.createOrderline(26, 1, 3);
        OrderlineRepository.createOrderline(26, 2, 1);
        OrderlineRepository.createOrderline(26, 3, 2);
        OrderlineRepository.createOrderline(27, 1, 3);
        OrderlineRepository.createOrderline(27, 2, 1);
        OrderlineRepository.createOrderline(27, 3, 2);
        OrderlineRepository.createOrderline(28, 1, 3);
        OrderlineRepository.createOrderline(28, 2, 1);
        OrderlineRepository.createOrderline(28, 3, 2);
        OrderlineRepository.createOrderline(29, 1, 3);
        OrderlineRepository.createOrderline(29, 2, 1);
        OrderlineRepository.createOrderline(29, 3, 2);
        OrderlineRepository.createOrderline(30, 1, 3);
        OrderlineRepository.createOrderline(30, 2, 1);
        OrderlineRepository.createOrderline(30, 3, 2);
        OrderlineRepository.createOrderline(31, 1, 3);
        OrderlineRepository.createOrderline(31, 2, 1);
        OrderlineRepository.createOrderline(31, 3, 2);
        OrderlineRepository.createOrderline(32, 1, 3);
        OrderlineRepository.createOrderline(32, 2, 1);
        OrderlineRepository.createOrderline(32, 3, 2);
        OrderlineRepository.createOrderline(33, 1, 3);
        OrderlineRepository.createOrderline(33, 2, 1);
        OrderlineRepository.createOrderline(33, 3, 2);
        OrderlineRepository.createOrderline(34, 1, 3);
        OrderlineRepository.createOrderline(34, 2, 1);
        OrderlineRepository.createOrderline(34, 3, 2);
        OrderlineRepository.createOrderline(35, 1, 3);
        OrderlineRepository.createOrderline(35, 2, 1);
        OrderlineRepository.createOrderline(35, 3, 2);
        OrderlineRepository.createOrderline(36, 1, 3);
        OrderlineRepository.createOrderline(36, 2, 1);
        OrderlineRepository.createOrderline(36, 3, 2);
        OrderlineRepository.createOrderline(37, 1, 3);
        OrderlineRepository.createOrderline(37, 2, 1);
        OrderlineRepository.createOrderline(37, 3, 2);
        OrderlineRepository.createOrderline(38, 1, 3);
        OrderlineRepository.createOrderline(38, 2, 1);
        OrderlineRepository.createOrderline(38, 3, 2);
        OrderlineRepository.createOrderline(39, 1, 3);
        OrderlineRepository.createOrderline(39, 2, 1);
        OrderlineRepository.createOrderline(39, 3, 2);
        OrderlineRepository.createOrderline(40, 1, 3);
        OrderlineRepository.createOrderline(40, 2, 1);
        OrderlineRepository.createOrderline(40, 3, 2);
        OrderlineRepository.createOrderline(41, 1, 3);
        OrderlineRepository.createOrderline(41, 2, 1);
        OrderlineRepository.createOrderline(41, 3, 2);
        OrderlineRepository.createOrderline(42, 1, 3);
        OrderlineRepository.createOrderline(42, 2, 1);
        OrderlineRepository.createOrderline(42, 3, 2);
        OrderlineRepository.createOrderline(43, 1, 3);
        OrderlineRepository.createOrderline(43, 2, 1);
        OrderlineRepository.createOrderline(43, 3, 2);
        OrderlineRepository.createOrderline(44, 1, 3);
        OrderlineRepository.createOrderline(44, 2, 1);
        OrderlineRepository.createOrderline(44, 3, 2);
        OrderlineRepository.createOrderline(45, 1, 3);
        OrderlineRepository.createOrderline(45, 2, 1);
        OrderlineRepository.createOrderline(45, 3, 2);
        OrderlineRepository.createOrderline(46, 1, 3);
        OrderlineRepository.createOrderline(46, 2, 1);
        OrderlineRepository.createOrderline(46, 3, 2);
        OrderlineRepository.createOrderline(47, 1, 3);
        OrderlineRepository.createOrderline(47, 2, 1);
        OrderlineRepository.createOrderline(47, 3, 2);
        OrderlineRepository.createOrderline(48, 1, 3);
        OrderlineRepository.createOrderline(48, 2, 1);
        OrderlineRepository.createOrderline(48, 3, 2);
        OrderlineRepository.createOrderline(49, 1, 3);
        OrderlineRepository.createOrderline(49, 2, 1);
        OrderlineRepository.createOrderline(49, 3, 2);
        OrderlineRepository.createOrderline(50, 1, 3);
        OrderlineRepository.createOrderline(50, 2, 1);
        OrderlineRepository.createOrderline(50, 3, 2);
        OrderlineRepository.createOrderline(51, 1, 3);
        OrderlineRepository.createOrderline(51, 2, 1);
        OrderlineRepository.createOrderline(51, 3, 2);
        OrderlineRepository.createOrderline(52, 1, 3);
        OrderlineRepository.createOrderline(52, 2, 1);
        OrderlineRepository.createOrderline(52, 3, 2);
        OrderlineRepository.createOrderline(53, 1, 3);
        OrderlineRepository.createOrderline(53, 2, 1);
        OrderlineRepository.createOrderline(53, 3, 2);
        OrderlineRepository.createOrderline(54, 1, 3);
        OrderlineRepository.createOrderline(54, 2, 1);
        OrderlineRepository.createOrderline(54, 3, 2);
        OrderlineRepository.createOrderline(55, 1, 3);
        OrderlineRepository.createOrderline(55, 2, 1);
        OrderlineRepository.createOrderline(55, 3, 2);
        OrderlineRepository.createOrderline(56, 1, 3);
        OrderlineRepository.createOrderline(56, 2, 1);
        OrderlineRepository.createOrderline(56, 3, 2);
        OrderlineRepository.createOrderline(57, 1, 3);
        OrderlineRepository.createOrderline(57, 2, 1);
        OrderlineRepository.createOrderline(57, 3, 2);
        OrderlineRepository.createOrderline(58, 1, 3);
        OrderlineRepository.createOrderline(58, 2, 1);
        OrderlineRepository.createOrderline(58, 3, 2);
        OrderlineRepository.createOrderline(59, 1, 3);
        OrderlineRepository.createOrderline(59, 2, 1);
        OrderlineRepository.createOrderline(59, 3, 2);
        OrderlineRepository.createOrderline(60, 1, 3);
        OrderlineRepository.createOrderline(60, 2, 1);
        OrderlineRepository.createOrderline(60, 3, 2);
        OrderlineRepository.createOrderline(61, 1, 3);
        OrderlineRepository.createOrderline(61, 2, 1);
        OrderlineRepository.createOrderline(61, 3, 2);
        OrderlineRepository.createOrderline(62, 1, 3);
        OrderlineRepository.createOrderline(62, 2, 1);
        OrderlineRepository.createOrderline(62, 3, 2);
        OrderlineRepository.createOrderline(63, 1, 3);
        OrderlineRepository.createOrderline(63, 2, 1);
        OrderlineRepository.createOrderline(63, 3, 2);
        OrderlineRepository.createOrderline(64, 1, 3);
        OrderlineRepository.createOrderline(64, 2, 1);
        OrderlineRepository.createOrderline(64, 3, 2);
        OrderlineRepository.createOrderline(65, 1, 3);
        OrderlineRepository.createOrderline(65, 2, 1);
        OrderlineRepository.createOrderline(65, 3, 2);
        OrderlineRepository.createOrderline(66, 1, 3);
        OrderlineRepository.createOrderline(66, 2, 1);
        OrderlineRepository.createOrderline(66, 3, 2);
        OrderlineRepository.createOrderline(67, 1, 3);
        OrderlineRepository.createOrderline(67, 2, 1);
        OrderlineRepository.createOrderline(67, 3, 2);
        OrderlineRepository.createOrderline(68, 1, 3);
        OrderlineRepository.createOrderline(68, 2, 1);
        OrderlineRepository.createOrderline(68, 3, 2);
        OrderlineRepository.createOrderline(69, 1, 3);
        OrderlineRepository.createOrderline(69, 2, 1);
        OrderlineRepository.createOrderline(69, 3, 2);
        OrderlineRepository.createOrderline(70, 1, 3);
        OrderlineRepository.createOrderline(70, 2, 1);
        OrderlineRepository.createOrderline(70, 3, 2);
        OrderlineRepository.createOrderline(71, 1, 3);
        OrderlineRepository.createOrderline(71, 2, 1);
        OrderlineRepository.createOrderline(71, 3, 2);
        OrderlineRepository.createOrderline(72, 1, 3);
        OrderlineRepository.createOrderline(72, 2, 1);
        OrderlineRepository.createOrderline(72, 3, 2);
        OrderlineRepository.createOrderline(73, 1, 3);
        OrderlineRepository.createOrderline(73, 2, 1);
        OrderlineRepository.createOrderline(73, 3, 2);
        OrderlineRepository.createOrderline(74, 1, 3);
        OrderlineRepository.createOrderline(74, 2, 1);
        OrderlineRepository.createOrderline(74, 3, 2);
        OrderlineRepository.createOrderline(75, 1, 3);
        OrderlineRepository.createOrderline(75, 2, 1);
        OrderlineRepository.createOrderline(75, 3, 2);
        OrderlineRepository.createOrderline(76, 1, 3);
        OrderlineRepository.createOrderline(76, 2, 1);
        OrderlineRepository.createOrderline(76, 3, 2);
        OrderlineRepository.createOrderline(77, 1, 3);
        OrderlineRepository.createOrderline(77, 2, 1);
        OrderlineRepository.createOrderline(77, 3, 2);
        OrderlineRepository.createOrderline(78, 1, 3);
        OrderlineRepository.createOrderline(78, 2, 1);
        OrderlineRepository.createOrderline(78, 3, 2);
        OrderlineRepository.createOrderline(79, 1, 3);
        OrderlineRepository.createOrderline(79, 2, 1);
        OrderlineRepository.createOrderline(79, 3, 2);
        OrderlineRepository.createOrderline(80, 1, 3);
        OrderlineRepository.createOrderline(80, 2, 1);
        OrderlineRepository.createOrderline(80, 3, 2);
        OrderlineRepository.createOrderline(81, 1, 3);
        OrderlineRepository.createOrderline(81, 2, 1);
        OrderlineRepository.createOrderline(81, 3, 2);
        OrderlineRepository.createOrderline(82, 1, 3);
        OrderlineRepository.createOrderline(82, 2, 1);
        OrderlineRepository.createOrderline(82, 3, 2);
        OrderlineRepository.createOrderline(83, 1, 3);
        OrderlineRepository.createOrderline(83, 2, 1);
        OrderlineRepository.createOrderline(83, 3, 2);
        OrderlineRepository.createOrderline(84, 1, 3);
        OrderlineRepository.createOrderline(84, 2, 1);
        OrderlineRepository.createOrderline(84, 3, 2);
        OrderlineRepository.createOrderline(85, 1, 3);
        OrderlineRepository.createOrderline(85, 2, 1);
        OrderlineRepository.createOrderline(85, 3, 2);
        OrderlineRepository.createOrderline(86, 1, 3);
        OrderlineRepository.createOrderline(86, 2, 1);
        OrderlineRepository.createOrderline(86, 3, 2);
        OrderlineRepository.createOrderline(87, 1, 3);
        OrderlineRepository.createOrderline(87, 2, 1);
        OrderlineRepository.createOrderline(87, 3, 2);
        OrderlineRepository.createOrderline(88, 1, 3);
        OrderlineRepository.createOrderline(88, 2, 1);
        OrderlineRepository.createOrderline(88, 3, 2);
        OrderlineRepository.createOrderline(89, 1, 3);
        OrderlineRepository.createOrderline(89, 2, 1);
        OrderlineRepository.createOrderline(89, 3, 2);
        OrderlineRepository.createOrderline(90, 1, 3);
        OrderlineRepository.createOrderline(90, 2, 1);
        OrderlineRepository.createOrderline(90, 3, 2);

        // CREATE STOCK
        StockRepository.createStock(1, 1, 0);
        StockRepository.createStock(1, 2, 5);
        StockRepository.createStock(1, 3, 10);
        StockRepository.createStock(2, 1, 0);
        StockRepository.createStock(2, 2, 5);
        StockRepository.createStock(2, 3, 10);
    }
}