package hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.initdatabases;

import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.CustomerRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.DistrictRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.EntityRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.ItemRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.OrderlineRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.StockRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.WarehouseRepository;

import java.util.HashMap;
import java.util.Map;


public class Main {
    public static void main (String[] args) {
    	EntityRepository.setUp();
        // CREATE WAREHOUSES
        WarehouseRepository.createWarehouse("Bergwald", "Fritz Falter");
        WarehouseRepository.createWarehouse("Echtwald", "Helga Hehl");

        // CREATE DISTRICTS
        DistrictRepository.createDistrict("Tellerheim", 10.0, 1);
        DistrictRepository.createDistrict("Gabelheim", 20.0, 1);
        DistrictRepository.createDistrict("Messerheim", 30.0, 1);
        DistrictRepository.createDistrict("Lichtheim", 40.0, 1);
        DistrictRepository.createDistrict("Loeffelheim", 50.0, 1);
        DistrictRepository.createDistrict("Tischheim", 60.0, 2);
        DistrictRepository.createDistrict("Sesselheim", 70.0, 2);
        DistrictRepository.createDistrict("Couchheim", 80.0, 2);
        DistrictRepository.createDistrict("Kastenheim", 90.0, 2);
        DistrictRepository.createDistrict("Papierheim", 100.0, 2);
        
        // CREATE ITEMS 
        ItemRepository.createItem("Monitor", 10.0);
        ItemRepository.createItem("Mouse", 20.0);
        ItemRepository.createItem("Keyboard", 30.0);

        // CREATE CUSTOMERS
        CustomerRepository.createCustomer("Emil", "Estermann", "Lessingstrasse 1", "0621 34562635", "123456789123", 1);
        CustomerRepository.createCustomer("Tina", "Tinker", "Bullenstrasse 2", "0621 34562636", "123456789124", 1);
        CustomerRepository.createCustomer("Franz", "Trulla", "Reisstrasse 5", "0621 34562637", "123456789125", 1);
        CustomerRepository.createCustomer("Jessica", "Blau", "Bildstrasse 5", "0621 34562638", "123456789126", 1);
        CustomerRepository.createCustomer("Tim", "Rot", "Kamerastrasse 5", "0621 34562639", "123456789127", 1);
        CustomerRepository.createCustomer("Eva", "Gelb", "Lichtstrasse 5", "0621 34562640", "123456789128", 2);
        CustomerRepository.createCustomer("Alex", "Orange", "Schalterstrasse 5", "0621 34562641", "123456789129", 2);
        CustomerRepository.createCustomer("Lara", "Lila", "Meterstrasse 5", "0621 34562642", "123456789130", 2);
        CustomerRepository.createCustomer("Felix", "Magenta", "Kaltstrasse 5", "0621 34562643", "123456789131", 2);
        CustomerRepository.createCustomer("Katrin", "Cyan", "Warmstrasse 5", "0621 34562644", "123456789132", 2);

        Map<Integer, Integer> map1 = new HashMap<Integer, Integer>(1, 3);
        Map<Integer, Integer> map2 = new HashMap<Integer, Integer>(2, 1);
        Map<Integer, Integer> map3 = new HashMap<Integer, Integer>(3, 2);
        
        // CREATE ORDER LINES
        OrderlineRepository.createOrderline(1, map1);
        OrderlineRepository.createOrderline(1, map2);
        OrderlineRepository.createOrderline(1, map3);
        OrderlineRepository.createOrderline(2, map1);
        OrderlineRepository.createOrderline(2, map2);
        OrderlineRepository.createOrderline(2, map3);
        OrderlineRepository.createOrderline(3, map1);
        OrderlineRepository.createOrderline(3, map2);
        OrderlineRepository.createOrderline(3, map3);
        OrderlineRepository.createOrderline(4, map1);
        OrderlineRepository.createOrderline(4, map2);
        OrderlineRepository.createOrderline(4, map3);
        OrderlineRepository.createOrderline(5, map1);
        OrderlineRepository.createOrderline(5, map2);
        OrderlineRepository.createOrderline(5, map3);
        OrderlineRepository.createOrderline(6, map1);
        OrderlineRepository.createOrderline(6, map2);
        OrderlineRepository.createOrderline(6, map3);
        OrderlineRepository.createOrderline(7, map1);
        OrderlineRepository.createOrderline(7, map2);
        OrderlineRepository.createOrderline(7, map3);
        OrderlineRepository.createOrderline(8, map1);
        OrderlineRepository.createOrderline(8, map2);
        OrderlineRepository.createOrderline(8, map3);
        OrderlineRepository.createOrderline(9, map1);
        OrderlineRepository.createOrderline(9, map2);
        OrderlineRepository.createOrderline(9, map3);
        OrderlineRepository.createOrderline(10, map1);
        OrderlineRepository.createOrderline(10, map2);
        OrderlineRepository.createOrderline(10, map3);
        OrderlineRepository.createOrderline(11, map1);
        OrderlineRepository.createOrderline(11, map2);
        OrderlineRepository.createOrderline(11, map3);
        OrderlineRepository.createOrderline(12, map1);
        OrderlineRepository.createOrderline(12, map2);
        OrderlineRepository.createOrderline(12, map3);
        OrderlineRepository.createOrderline(13, map1);
        OrderlineRepository.createOrderline(13, map2);
        OrderlineRepository.createOrderline(13, map3);
        OrderlineRepository.createOrderline(14, map1);
        OrderlineRepository.createOrderline(14, map2);
        OrderlineRepository.createOrderline(14, map3);
        OrderlineRepository.createOrderline(15, map1);
        OrderlineRepository.createOrderline(15, map2);
        OrderlineRepository.createOrderline(15, map3);
        OrderlineRepository.createOrderline(16, map1);
        OrderlineRepository.createOrderline(16, map2);
        OrderlineRepository.createOrderline(16, map3);
        OrderlineRepository.createOrderline(17, map1);
        OrderlineRepository.createOrderline(17, map2);
        OrderlineRepository.createOrderline(17, map3);
        OrderlineRepository.createOrderline(18, map1);
        OrderlineRepository.createOrderline(18, map2);
        OrderlineRepository.createOrderline(18, map3);
        OrderlineRepository.createOrderline(19, map1);
        OrderlineRepository.createOrderline(19, map2);
        OrderlineRepository.createOrderline(19, map3);
        OrderlineRepository.createOrderline(20, map1);
        OrderlineRepository.createOrderline(20, map2);
        OrderlineRepository.createOrderline(20, map3);
        OrderlineRepository.createOrderline(21, map1);
        OrderlineRepository.createOrderline(21, map2);
        OrderlineRepository.createOrderline(21, map3);
        OrderlineRepository.createOrderline(22, map1);
        OrderlineRepository.createOrderline(22, map2);
        OrderlineRepository.createOrderline(22, map3);
        OrderlineRepository.createOrderline(23, map1);
        OrderlineRepository.createOrderline(23, map2);
        OrderlineRepository.createOrderline(23, map3);
        OrderlineRepository.createOrderline(24, map1);
        OrderlineRepository.createOrderline(24, map2);
        OrderlineRepository.createOrderline(24, map3);
        OrderlineRepository.createOrderline(25, map1);
        OrderlineRepository.createOrderline(25, map2);
        OrderlineRepository.createOrderline(25, map3);
        OrderlineRepository.createOrderline(26, map1);
        OrderlineRepository.createOrderline(26, map2);
        OrderlineRepository.createOrderline(26, map3);
        OrderlineRepository.createOrderline(27, map1);
        OrderlineRepository.createOrderline(27, map2);
        OrderlineRepository.createOrderline(27, map3);
        OrderlineRepository.createOrderline(28, map1);
        OrderlineRepository.createOrderline(28, map2);
        OrderlineRepository.createOrderline(28, map3);
        OrderlineRepository.createOrderline(29, map1);
        OrderlineRepository.createOrderline(29, map2);
        OrderlineRepository.createOrderline(29, map3);
        OrderlineRepository.createOrderline(30, map1);
        OrderlineRepository.createOrderline(30, map2);
        OrderlineRepository.createOrderline(30, map3);
        OrderlineRepository.createOrderline(31, map1);
        OrderlineRepository.createOrderline(31, map2);
        OrderlineRepository.createOrderline(31, map3);
        OrderlineRepository.createOrderline(32, map1);
        OrderlineRepository.createOrderline(32, map2);
        OrderlineRepository.createOrderline(32, map3);
        OrderlineRepository.createOrderline(33, map1);
        OrderlineRepository.createOrderline(33, map2);
        OrderlineRepository.createOrderline(33, map3);
        OrderlineRepository.createOrderline(34, map1);
        OrderlineRepository.createOrderline(34, map2);
        OrderlineRepository.createOrderline(34, map3);
        OrderlineRepository.createOrderline(35, map1);
        OrderlineRepository.createOrderline(35, map2);
        OrderlineRepository.createOrderline(35, map3);
        OrderlineRepository.createOrderline(36, map1);
        OrderlineRepository.createOrderline(36, map2);
        OrderlineRepository.createOrderline(36, map3);
        OrderlineRepository.createOrderline(37, map1);
        OrderlineRepository.createOrderline(37, map2);
        OrderlineRepository.createOrderline(37, map3);
        OrderlineRepository.createOrderline(38, map1);
        OrderlineRepository.createOrderline(38, map2);
        OrderlineRepository.createOrderline(38, map3);
        OrderlineRepository.createOrderline(39, map1);
        OrderlineRepository.createOrderline(39, map2);
        OrderlineRepository.createOrderline(39, map3);
        OrderlineRepository.createOrderline(40, map1);
        OrderlineRepository.createOrderline(40, map2);
        OrderlineRepository.createOrderline(40, map3);
        OrderlineRepository.createOrderline(41, map1);
        OrderlineRepository.createOrderline(41, map2);
        OrderlineRepository.createOrderline(41, map3);
        OrderlineRepository.createOrderline(42, map1);
        OrderlineRepository.createOrderline(42, map2);
        OrderlineRepository.createOrderline(42, map3);
        OrderlineRepository.createOrderline(43, map1);
        OrderlineRepository.createOrderline(43, map2);
        OrderlineRepository.createOrderline(43, map3);
        OrderlineRepository.createOrderline(44, map1);
        OrderlineRepository.createOrderline(44, map2);
        OrderlineRepository.createOrderline(44, map3);
        OrderlineRepository.createOrderline(45, map1);
        OrderlineRepository.createOrderline(45, map2);
        OrderlineRepository.createOrderline(45, map3);
        OrderlineRepository.createOrderline(46, map1);
        OrderlineRepository.createOrderline(46, map2);
        OrderlineRepository.createOrderline(46, map3);
        OrderlineRepository.createOrderline(47, map1);
        OrderlineRepository.createOrderline(47, map2);
        OrderlineRepository.createOrderline(47, map3);
        OrderlineRepository.createOrderline(48, map1);
        OrderlineRepository.createOrderline(48, map2);
        OrderlineRepository.createOrderline(48, map3);
        OrderlineRepository.createOrderline(49, map1);
        OrderlineRepository.createOrderline(49, map2);
        OrderlineRepository.createOrderline(49, map3);
        OrderlineRepository.createOrderline(50, map1);
        OrderlineRepository.createOrderline(50, map2);
        OrderlineRepository.createOrderline(50, map3);
        OrderlineRepository.createOrderline(51, map1);
        OrderlineRepository.createOrderline(51, map2);
        OrderlineRepository.createOrderline(51, map3);
        OrderlineRepository.createOrderline(52, map1);
        OrderlineRepository.createOrderline(52, map2);
        OrderlineRepository.createOrderline(52, map3);
        OrderlineRepository.createOrderline(53, map1);
        OrderlineRepository.createOrderline(53, map2);
        OrderlineRepository.createOrderline(53, map3);
        OrderlineRepository.createOrderline(54, map1);
        OrderlineRepository.createOrderline(54, map2);
        OrderlineRepository.createOrderline(54, map3);
        OrderlineRepository.createOrderline(55, map1);
        OrderlineRepository.createOrderline(55, map2);
        OrderlineRepository.createOrderline(55, map3);
        OrderlineRepository.createOrderline(56, map1);
        OrderlineRepository.createOrderline(56, map2);
        OrderlineRepository.createOrderline(56, map3);
        OrderlineRepository.createOrderline(57, map1);
        OrderlineRepository.createOrderline(57, map2);
        OrderlineRepository.createOrderline(57, map3);
        OrderlineRepository.createOrderline(58, map1);
        OrderlineRepository.createOrderline(58, map2);
        OrderlineRepository.createOrderline(58, map3);
        OrderlineRepository.createOrderline(59, map1);
        OrderlineRepository.createOrderline(59, map2);
        OrderlineRepository.createOrderline(59, map3);
        OrderlineRepository.createOrderline(60, map1);
        OrderlineRepository.createOrderline(60, map2);
        OrderlineRepository.createOrderline(60, map3);
        OrderlineRepository.createOrderline(61, map1);
        OrderlineRepository.createOrderline(61, map2);
        OrderlineRepository.createOrderline(61, map3);
        OrderlineRepository.createOrderline(62, map1);
        OrderlineRepository.createOrderline(62, map2);
        OrderlineRepository.createOrderline(62, map3);
        OrderlineRepository.createOrderline(63, map1);
        OrderlineRepository.createOrderline(63, map2);
        OrderlineRepository.createOrderline(63, map3);
        OrderlineRepository.createOrderline(64, map1);
        OrderlineRepository.createOrderline(64, map2);
        OrderlineRepository.createOrderline(64, map3);
        OrderlineRepository.createOrderline(65, map1);
        OrderlineRepository.createOrderline(65, map2);
        OrderlineRepository.createOrderline(65, map3);
        OrderlineRepository.createOrderline(66, map1);
        OrderlineRepository.createOrderline(66, map2);
        OrderlineRepository.createOrderline(66, map3);
        OrderlineRepository.createOrderline(67, map1);
        OrderlineRepository.createOrderline(67, map2);
        OrderlineRepository.createOrderline(67, map3);
        OrderlineRepository.createOrderline(68, map1);
        OrderlineRepository.createOrderline(68, map2);
        OrderlineRepository.createOrderline(68, map3);
        OrderlineRepository.createOrderline(69, map1);
        OrderlineRepository.createOrderline(69, map2);
        OrderlineRepository.createOrderline(69, map3);
        OrderlineRepository.createOrderline(70, map1);
        OrderlineRepository.createOrderline(70, map2);
        OrderlineRepository.createOrderline(70, map3);
        OrderlineRepository.createOrderline(71, map1);
        OrderlineRepository.createOrderline(71, map2);
        OrderlineRepository.createOrderline(71, map3);
        OrderlineRepository.createOrderline(72, map1);
        OrderlineRepository.createOrderline(72, map2);
        OrderlineRepository.createOrderline(72, map3);
        OrderlineRepository.createOrderline(73, map1);
        OrderlineRepository.createOrderline(73, map2);
        OrderlineRepository.createOrderline(73, map3);
        OrderlineRepository.createOrderline(74, map1);
        OrderlineRepository.createOrderline(74, map2);
        OrderlineRepository.createOrderline(74, map3);
        OrderlineRepository.createOrderline(75, map1);
        OrderlineRepository.createOrderline(75, map2);
        OrderlineRepository.createOrderline(75, map3);
        OrderlineRepository.createOrderline(76, map1);
        OrderlineRepository.createOrderline(76, map2);
        OrderlineRepository.createOrderline(76, map3);
        OrderlineRepository.createOrderline(77, map1);
        OrderlineRepository.createOrderline(77, map2);
        OrderlineRepository.createOrderline(77, map3);
        OrderlineRepository.createOrderline(78, map1);
        OrderlineRepository.createOrderline(78, map2);
        OrderlineRepository.createOrderline(78, map3);
        OrderlineRepository.createOrderline(79, map1);
        OrderlineRepository.createOrderline(79, map2);
        OrderlineRepository.createOrderline(79, map3);
        OrderlineRepository.createOrderline(80, map1);
        OrderlineRepository.createOrderline(80, map2);
        OrderlineRepository.createOrderline(80, map3);
        OrderlineRepository.createOrderline(81, map1);
        OrderlineRepository.createOrderline(81, map2);
        OrderlineRepository.createOrderline(81, map3);
        OrderlineRepository.createOrderline(82, map1);
        OrderlineRepository.createOrderline(82, map2);
        OrderlineRepository.createOrderline(82, map3);
        OrderlineRepository.createOrderline(83, map1);
        OrderlineRepository.createOrderline(83, map2);
        OrderlineRepository.createOrderline(83, map3);
        OrderlineRepository.createOrderline(84, map1);
        OrderlineRepository.createOrderline(84, map2);
        OrderlineRepository.createOrderline(84, map3);
        OrderlineRepository.createOrderline(85, map1);
        OrderlineRepository.createOrderline(85, map2);
        OrderlineRepository.createOrderline(85, map3);
        OrderlineRepository.createOrderline(86, map1);
        OrderlineRepository.createOrderline(86, map2);
        OrderlineRepository.createOrderline(86, map3);
        OrderlineRepository.createOrderline(87, map1);
        OrderlineRepository.createOrderline(87, map2);
        OrderlineRepository.createOrderline(87, map3);
        OrderlineRepository.createOrderline(88, map1);
        OrderlineRepository.createOrderline(88, map2);
        OrderlineRepository.createOrderline(88, map3);
        OrderlineRepository.createOrderline(89, map1);
        OrderlineRepository.createOrderline(89, map2);
        OrderlineRepository.createOrderline(89, map3);
        OrderlineRepository.createOrderline(90, map1);
        OrderlineRepository.createOrderline(90, map2);
        OrderlineRepository.createOrderline(90, map3);

        // CREATE STOCK
        StockRepository.createStock(1, 1, 0);
        StockRepository.createStock(1, 2, 5);
        StockRepository.createStock(1, 3, 10);
        StockRepository.createStock(2, 1, 0);
        StockRepository.createStock(2, 2, 5);
        StockRepository.createStock(2, 3, 10);
        
		EntityRepository.exit();
    }
}