package hsma.ss2018.informatik.igt.kohler.javawithhibernate;

import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.CustomerRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.DistrictRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.ItemRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.OrderlineRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.OrderRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.StockRepository;
import hsma.ss2018.informatik.igt.kohler.javawithhibernate.control.WarehouseRepository;
import java.util.Map;


public class Main {
    public static void main (String[] args) {

        // CREATE WAREHOUSES
        WarehouseRepository.createWarehouse("Bergwald", "Fritz Falter");
        WarehouseRepository.createWarehouse("Echtwald", "Helga Hehl");

        // CREATE DISTRICTS
        DistrictRepository.createDistrict("Tellerheim", 10.0, 1);
        DistrictRepository.createDistrict("Gabelheim", 20.0, 1);
        DistrictRepository.createDistrict("Messerheim", 30.0, 1);
        DistrictRepository.createDistrict("Lichtheim", 40.0, 1);
        DistrictRepository.createDistrict("Loeffelheim", 50.0, 1);
        DistrictRepository.createDistrict("Tischheim", 60.0, 2);
        DistrictRepository.createDistrict("Sesselheim", 70.0, 2);
        DistrictRepository.createDistrict("Couchheim", 80.0, 2);
        DistrictRepository.createDistrict("Kastenheim", 90.0, 2);
        DistrictRepository.createDistrict("Papierheim", 100.0, 2);
        
        // CREATE ITEMS 
        ItemRepository.createItem("Monitor", 10.0);
        ItemRepository.createItem("Mouse", 20.0);
        ItemRepository.createItem("Keyboard" 30.0);

        // CREATE CUSTOMERS
        CustomerRepository.createCustomer("Emil", "Estermann", "Lessingstrasse 1", "0621 34562635", "123456789123", 1);
        CustomerRepository.createCustomer("Tina", "Tinker", "Bullenstrasse 2", "0621 34562636", "123456789124", 1);
        CustomerRepository.createCustomer("Franz", "Trulla", "Reisstrasse 5", "0621 34562637", "123456789125", 1);
        CustomerRepository.createCustomer("Jessica", "Blau", "Bildstrasse 5", "0621 34562638", "123456789126", 1);
        CustomerRepository.createCustomer("Tim", "Rot", "Kamerastrasse 5", "0621 34562639", "123456789127", 1);
        CustomerRepository.createCustomer("Eva", "Gelb", "Lichtstrasse 5", "0621 34562640", "123456789128", 2);
        CustomerRepository.createCustomer("Alex", "Orange", "Schalterstrasse 5", "0621 34562641", "123456789129", 2);
        CustomerRepository.createCustomer("Lara", "Lila", "Meterstrasse 5", "0621 34562642", "123456789130", 2);
        CustomerRepository.createCustomer("Felix", "Magenta", "Kaltstrasse 5", "0621 34562643", "123456789131", 2);
        CustomerRepository.createCustomer("Katrin", "Cyan", "Warmstrasse 5", "0621 34562644", "123456789132", 2);

        // CREATE ORDER LINES
        OrderlineRepository.createOrderline(1, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(1, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(1, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(2, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(2, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(2, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(3, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(3, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(3, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(4, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(4, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(4, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(5, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(5, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(5, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(6, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(6, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(6, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(7, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(7, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(7, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(8, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(8, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(8, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(9, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(9, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(9, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(10, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(10, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(10, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(11, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(11, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(11, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(12, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(12, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(12, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(13, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(13, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(13, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(14, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(14, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(14, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(15, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(15, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(15, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(16, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(16, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(16, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(17, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(17, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(17, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(18, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(18, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(18, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(19, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(19, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(19, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(20, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(20, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(20, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(21, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(21, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(21, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(22, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(22, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(22, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(23, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(23, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(23, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(24, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(24, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(24, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(25, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(25, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(25, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(26, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(26, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(26, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(27, Map<Integer, Integer>(1, 3);
        OrderlineRepository.createOrderline(27, Map<Integer, Integer>(2, 1);
        OrderlineRepository.createOrderline(27, Map<Integer, Integer>(3, 2);
        OrderlineRepository.createOrderline(28, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(28, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(28, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(29, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(29, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(29, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(30, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(30, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(30, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(31, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(31, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(31, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(32, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(32, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(32, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(33, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(33, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(33, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(34, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(34, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(34, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(35, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(35, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(35, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(36, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(36, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(36, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(37, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(37, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(37, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(38, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(38, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(38, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(39, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(39, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(39, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(40, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(40, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(40, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(41, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(41, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(41, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(42, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(42, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(42, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(43, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(43, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(43, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(44, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(44, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(44, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(45, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(45, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(45, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(46, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(46, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(46, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(47, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(47, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(47, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(48, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(48, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(48, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(49, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(49, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(49, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(50, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(50, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(50, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(51, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(51, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(51, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(52, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(52, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(52, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(53, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(53, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(53, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(54, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(54, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(54, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(55, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(55, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(55, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(56, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(56, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(56, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(57, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(57, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(57, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(58, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(58, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(58, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(59, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(59, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(59, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(60, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(60, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(60, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(61, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(61, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(61, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(62, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(62, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(62, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(63, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(63, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(63, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(64, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(64, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(64, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(65, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(65, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(65, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(66, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(66, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(66, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(67, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(67, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(67, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(68, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(68, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(68, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(69, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(69, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(69, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(70, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(70, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(70, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(71, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(71, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(71, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(72, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(72, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(72, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(73, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(73, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(73, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(74, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(74, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(74, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(75, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(75, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(75, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(76, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(76, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(76, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(77, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(77, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(77, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(78, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(78, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(78, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(79, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(79, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(79, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(80, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(80, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(80, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(81, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(81, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(81, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(82, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(82, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(82, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(83, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(83, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(83, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(84, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(84, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(84, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(85, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(85, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(85, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(86, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(86, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(86, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(87, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(87, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(87, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(88, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(88, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(88, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(89, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(89, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(89, Map<Integer, Integer>(3, 2));
        OrderlineRepository.createOrderline(90, Map<Integer, Integer>(1, 3));
        OrderlineRepository.createOrderline(90, Map<Integer, Integer>(2, 1));
        OrderlineRepository.createOrderline(90, Map<Integer, Integer>(3, 2));

        // CREATE STOCK
        StockRepository.createStock(1, 1, 0);
        StockRepository.createStock(1, 2, 5);
        StockRepository.createStock(1, 3, 10);
        StockRepository.createStock(2, 1, 0);
        StockRepository.createStock(2, 2, 5);
        StockRepository.createStock(2, 3, 10);
    }
}