version: '3.6'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: igtDatabase
    volumes:
      - ./IGT_Aufgabe2_Tabellen.sql:/docker-entrypoint-initdb.d/IGT_Aufgabe2_Tabellen.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: 172.18.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerOrderManager
      
  ormapplicationontomcat:
    build: .
    ports: 
      - "8080:8080"