drop database if exists customerOrderManager;
create database if not exists customerOrderManager;
use customerOrderManager;

/*Tables representig the entities*/
create table if not exists WAREHOUSES(WarehouseId int not null auto_increment, Location varchar(50), WarehouseOwner char(60), primary key(WarehouseId));
create table if not exists DISTRICTS(DistrictId int not null auto_increment, Location varchar(50), WarehouseId int not null, primary key(DistrictId), foreign key(WarehouseId) references WAREHOUSES(WarehouseId));
create table if not exists CUSTOMERS(CustomerId int not null auto_increment, FirstName varchar(30), LastName varchar(30), Address varchar(50), Telephone varchar(15), KreditCardNr varchar(12), DistrictId int not null,  primary key(CustomerId), foreign key(DistrictId) references DISTRICTS(DistrictId));
create table if not exists ORDERS(OrderId int not null auto_increment, OrderDate date, CustomerId int not null, primary key(OrderId), foreign key(CustomerId) references CUSTOMERS(CustomerId));
create table if not exists ITEMS(ItemId int not null auto_increment, ItemName varchar(50), primary key(ItemId));

/*Many-to-Many Relationships*/
create table if not exists ORDERLINES(ItemId int not null, OrderId int not null, Quantity int default 0, primary key(ItemId, OrderId), foreign key(ItemId) references ITEMS(ItemId), foreign key(OrderId) references ORDERS(OrderId));
create table if not exists STOCKS(ItemId int not null, WarehouseId int not null, Quantity int default 0, primary key(ItemId, WarehouseId), foreign key(ItemId) references ITEMS(ItemId), foreign key(WarehouseId) references WAREHOUSES(WarehouseId));

/*Views on the orders ORDERSOVERYEAR mean */
create view ORDERSOVERYEAR as select OrderId, OrderDate, CustomerId from ORDERS where Date(OrderDate) < '2018-01-01 00:00:00';
create view NEWORDERS as select OrderId, OrderDate, CustomerId from ORDERS where Date(OrderDate) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY);


/*Data for WAREHOUSES*/
insert into WAREHOUSES(Location, WarehouseOwner) values('Bergwald', 'Fritz Falter');
insert into WAREHOUSES(Location, WarehouseOwner) values('Echtwald', 'Helga Hehl');

/*Date for DISTRICTS*/
insert into DISTRICTS(Location, WarehouseId) values('Tellerheim', 1);
insert into DISTRICTS(Location, WarehouseId) values('Gabelheim', 1);
insert into DISTRICTS(Location, WarehouseId) values('Messerheim', 1);
insert into DISTRICTS(Location, WarehouseId) values('Lichtheim', 1);
insert into DISTRICTS(Location, WarehouseId) values('Loeffelheim', 1);
insert into DISTRICTS(Location, WarehouseId) values('Tischheim', 2);
insert into DISTRICTS(Location, WarehouseId) values('Sesselheim', 2);
insert into DISTRICTS(Location, WarehouseId) values('Coucheheim', 2);
insert into DISTRICTS(Location, WarehouseId) values('Kastenheim', 2);
insert into DISTRICTS(Location, WarehouseId) values('Papierheim', 2);

/*Data for CUSTOMERS*/
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Emil', 'Estermann', 'Lessingstrasse 1', '0621 34562635', '123456789123', 1);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Tina', 'Tinker', 'Bullenstrasse 2', '0621 34562636', '123456789124', 1);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Franz', 'Trulla', 'Reisstrasse 5', '0621 34562637', '123456789125', 1);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Jessica', 'Blau', 'Bildstrasse 5', '0621 34562638', '123456789126', 1);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Tim', 'Rot', 'Kamerastrasse 5', '0621 34562639', '123456789127', 1);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Eva', 'Gelb', 'Lichtstrasse 5', '0621 34562640', '123456789128', 2);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Alex', 'Orange', 'Schalterstrasse 5', '0621 34562641', '123456789129', 2);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Lara', 'Lila', 'Meterstrasse 5', '0621 34562642', '123456789130', 2);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Felix', 'Magenta', 'Kaltstrasse 5', '0621 34562643', '123456789131', 2);
insert into CUSTOMERS(FirstName, LastName, Address, Telephone, KreditCardNr, DistrictId) values('Katrin', 'Cyan', 'Warmstrasse 5', '0621 34562644', '123456789132', 2);

/*Data for ORDERS*/
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 1);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 2);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 3);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 4);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 5);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 6);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 7);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 8);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 9);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-01 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-02 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2017-06-03 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-04 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-05 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-01-06 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 10);
insert into ORDERS(OrderDate, CustomerId) values('2018-05-16 00:00:00', 10);

/*Data for ITEMS*/
insert into ITEMS(ItemName) values('Monitor');
insert into ITEMS(ItemName) values('Mouse');
insert into ITEMS(ItemName) values('Keyboard');

/*Data for ORDERLINES*/
insert into ORDERLINES(OrderId, ItemId, Quantity) values(1, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(1, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(1, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(2, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(2, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(2, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(3, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(3, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(3, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(4, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(4, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(4, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(5, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(5, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(5, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(6, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(6, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(6, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(7, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(7, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(7, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(8, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(8, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(8, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(9, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(9, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(9, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(10, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(10, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(10, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(11, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(11, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(11, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(12, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(12, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(12, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(13, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(13, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(13, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(14, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(14, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(14, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(15, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(15, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(15, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(16, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(16, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(16, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(17, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(17, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(17, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(18, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(18, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(18, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(19, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(19, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(19, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(20, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(20, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(20, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(21, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(21, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(21, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(22, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(22, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(22, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(23, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(23, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(23, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(24, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(24, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(24, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(25, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(25, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(25, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(26, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(26, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(26, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(27, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(27, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(27, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(28, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(28, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(28, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(29, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(29, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(29, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(30, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(30, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(30, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(31, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(31, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(31, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(32, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(32, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(32, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(33, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(33, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(33, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(34, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(34, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(34, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(35, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(35, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(35, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(36, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(36, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(36, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(37, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(37, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(37, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(38, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(38, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(38, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(39, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(39, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(39, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(40, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(40, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(40, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(41, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(41, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(41, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(42, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(42, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(42, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(43, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(43, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(43, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(44, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(44, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(44, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(45, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(45, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(45, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(46, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(46, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(46, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(47, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(47, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(47, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(48, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(48, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(48, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(49, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(49, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(49, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(50, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(50, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(50, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(51, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(51, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(51, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(52, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(52, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(52, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(53, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(53, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(53, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(54, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(54, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(54, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(55, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(55, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(55, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(56, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(56, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(56, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(57, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(57, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(57, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(58, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(58, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(58, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(59, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(59, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(59, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(60, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(60, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(60, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(61, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(61, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(61, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(62, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(62, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(62, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(63, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(63, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(63, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(64, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(64, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(64, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(65, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(65, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(65, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(66, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(66, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(66, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(67, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(67, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(67, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(68, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(68, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(68, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(69, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(69, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(69, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(70, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(70, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(70, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(71, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(71, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(71, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(72, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(72, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(72, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(73, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(73, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(73, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(74, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(74, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(74, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(75, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(75, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(75, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(76, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(76, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(76, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(77, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(77, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(77, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(78, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(78, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(78, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(79, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(79, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(79, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(80, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(80, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(80, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(81, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(81, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(81, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(82, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(82, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(82, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(83, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(83, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(83, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(84, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(84, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(84, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(85, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(85, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(85, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(86, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(86, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(86, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(87, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(87, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(87, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(88, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(88, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(88, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(89, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(89, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(89, 3, 2);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(90, 1, 3);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(90, 2, 1);
insert into ORDERLINES(OrderId, ItemId, Quantity) values(90, 3, 2);

/*Data for STOCKS*/
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(1, 1, 0);
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(1, 2, 5);
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(1, 3, 10);
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(2, 1, 0);
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(2, 2, 5);
insert into STOCKS(WarehouseId, ItemId, Quantity) Values(2, 3, 10);